In [1]:
import dynet as dy
import numpy as np

# `dyNet` basics

## `dyNet` data structures

At it's basic level, `dyNet` is utilizing `tensor`s (multidimensional structures).

![tensors](images/tensors.png)

In [2]:
# scalar
sample_scalar = dy.scalarInput(5)

In [3]:
# vector (1 x 5)
sample_vector = dy.inputTensor(
    [1,2,3,4,5]
)

In [4]:
# matrix (2 x 5)
sample_matrix = dy.inputTensor(
    [
        [1,2,3,4,5],
        [6,7,8,9,10]
    ]
)

In [5]:
# 3-d tensor (2 X 2 x 5)
sample_tensor = dy.inputTensor(
    [
        [
            [1,3,5,7,9],
            [2,4,6,8,10]
        ],
        [
            [11,13,15,17,19],
            [12,14,16,18,20]
        ]
    ]
)

## computational graphs

`dynet`, like many other popular packages out there (`tensorflow`, `pytorch`, `mxnet`, `chainer`), is a **computational graph** library.

You build a `directed graph` of computations you'd like to make, and then they are executed all at once.


### `dyNet` expressions

And so, everything (even the `tensor`s we made above) in `dyNet` is made into an `expression`.

In [6]:
for i in [sample_scalar, sample_matrix, sample_tensor]:
          print(type(sample_scalar))

<class '_dynet._inputExpression'>
<class '_dynet._inputExpression'>
<class '_dynet._inputExpression'>


To **access** the values of the `tensor`s, we use the methods `.value()` and  `.npvalue()`:

 - `.value()` will return it as a `python` data structure
 - `.npvalue()` will return it as a `numpy` data structure

#### `scalar`s

Note: calling `.npvalue()` on a `scalar` will give you an unnecessary `vector`.  `.value()` should be used for `scalar`s.

In [7]:
sample_scalar.value()

5.0

In [8]:
sample_scalar.npvalue()

array([ 5.])

In [9]:
sample_scalar.npvalue().shape

(1,)

#### `tensor`s

Likewise, calling `.value()` on a `tensor` will return a `python` object, not a `numpy` object.  Not helpful....use `.npvalue()`

In [10]:
sample_vector.value()      # do *not* use .value()

[1.0, 2.0, 3.0, 4.0, 5.0]

In [11]:
sample_vector.npvalue()

array([ 1.,  2.,  3.,  4.,  5.])

In [12]:
sample_vector.npvalue().shape

(5,)

In [13]:
sample_matrix.npvalue().shape

(2, 5)

In [14]:
sample_tensor.npvalue().shape

(2, 2, 5)

#### other `expression`s

`expression`s can also be computations on our data structures...

In [15]:
# elementwise addition on a vector
add_expression = sample_vector + 5

...and even computations on other `expression`s.

In [16]:
# elementwise multiplication on the resulting vector above
mult_expression = add_expression * 3

The calculations of an `expression` are not carried out **until** you call `.value()` or `.npvalue()`

In [17]:
# step 1: the vector
sample_vector.npvalue()

array([ 1.,  2.,  3.,  4.,  5.])

In [18]:
# step 2: elementwise addition
add_expression.npvalue()

array([  6.,   7.,   8.,   9.,  10.])

In [19]:
# step 3: elementwise multiplication
mult_expression.npvalue()

array([ 18.,  21.,  24.,  27.,  30.])

The full computational graph can be seen below:

![viz](images/graph_viz.jpg)

Note: There's no "easy" way to generate this image from inside a `jupyter` `notebook`, so I didn't bother to include the commands.

### "dynamic" computational graph

`dyNet` is different from some other packages in that this graph creation is done for **each** data point, and so it can easily change.

This will become **enormously** helpful when we get into sequential (recurrent) neural networks (`RNN`s).

In [20]:
for i in range(4):
    print("data point {}".format(i + 1))
    # you *must* call `.renew_cg()` each time you want to build a "new" computational graph
    dy.renew_cg()
    # generate a *different* sized vector for each `i`
    starting_vector = dy.inputTensor([i+5] * (i+5))      
    print("starting vector", starting_vector.npvalue())
    # change the elementwise multiplication value for each `i`
    calculation = starting_vector * i
    print("multiplying by {}".format(i), calculation.npvalue())
    print("-------")

data point 1
starting vector [ 5.  5.  5.  5.  5.]
multiplying by 0 [ 0.  0.  0.  0.  0.]
-------
data point 2
starting vector [ 6.  6.  6.  6.  6.  6.]
multiplying by 1 [ 6.  6.  6.  6.  6.  6.]
-------
data point 3
starting vector [ 7.  7.  7.  7.  7.  7.  7.]
multiplying by 2 [ 14.  14.  14.  14.  14.  14.  14.]
-------
data point 4
starting vector [ 8.  8.  8.  8.  8.  8.  8.  8.]
multiplying by 3 [ 24.  24.  24.  24.  24.  24.  24.  24.]
-------


## your turn...

You should now be able to do the following:

  1. build the following data structures:
    - `[ [ 5 5 5 5 5 ] [ 5 5 5 5 5 ] [ 5 5 5 5 5] ]` (shape=`3x5`) 
    - `[ 1 2 3 ]` (shape=`1x3`)

  2. build an expression to get their product using `matrix multiplication` 
    - **HINT**: in `dyNet` you can just use `*` but you'll have to be aware of the dimensions of each object and the order they are written in
    
  3. BONUS: write a `for` loop using the "dynamic" computational power of `dyNet` where you increase the values of the first `1x5` vector by `i`

In [21]:
# your code here
# use the toolbar above to add/remove cells
# CTRL+enter will execute the cell